"""added immutable column

Revision ID: 29d2e30dee1b
Revises: f84c0e0cdb7e
Create Date: 2026-02-15 02:05:17.333116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d2e30dee1b'
down_revision: Union[str, Sequence[str], None] = 'f84c0e0cdb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('immutable', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='users')
    op.alter_column('user_auth', 'api_key_hash',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='users')
    
    op.execute("""
        UPDATE users.user
        SET immutable = true
        WHERE username = 'admin'
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_auth', 'api_key_hash',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='users')
    op.drop_column('user', 'immutable', schema='users')
    # ### end Alembic commands ###
