"""fixed default values

Revision ID: 2c3b46f94269
Revises: 1d9df8cdc427
Create Date: 2026-01-25 03:22:12.014685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c3b46f94269'
down_revision: Union[str, Sequence[str], None] = '1d9df8cdc427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_perm', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='users')
    op.alter_column('user_perm', 'activated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_perm', 'activated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='users')
    op.alter_column('user_perm', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='users')
    # ### end Alembic commands ###
