"""reverted test migration

Revision ID: 546a9c0f4f47
Revises: f92d00933ffa
Create Date: 2026-01-28 20:04:43.734679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546a9c0f4f47'
down_revision: Union[str, Sequence[str], None] = 'f92d00933ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table', schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('test_table_pkey')),
    schema='users'
    )
    # ### end Alembic commands ###
