"""testing migration logs v2

Revision ID: 6322f6de6b84
Revises: eb7048e0182f
Create Date: 2026-01-31 00:05:53.024861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6322f6de6b84'
down_revision: Union[str, Sequence[str], None] = 'eb7048e0182f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test2',
    sa.Column('test_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('test_id'),
    schema='internal'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test2', schema='internal')
    # ### end Alembic commands ###
