"""revert changes for testing migration logging

Revision ID: 8012d775a881
Revises: 6322f6de6b84
Create Date: 2026-01-31 00:12:58.214508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8012d775a881'
down_revision: Union[str, Sequence[str], None] = '6322f6de6b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testg', schema='internal')
    op.drop_table('test2', schema='internal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    print("Downgrade not recommendet")
    exit(1) # <- add comment here
    op.create_table('test2',
    sa.Column('test_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('test_id', name=op.f('test2_pkey')),
    schema='internal'
    )
    op.create_table('testg',
    sa.Column('test_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('test_id', name=op.f('testg_pkey')),
    schema='internal'
    )
    # ### end Alembic commands ###
