"""add migration log

Revision ID: 994b2fac8a00
Revises: d5f4f14afbe6
Create Date: 2026-01-30 23:26:50.532278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994b2fac8a00'
down_revision: Union[str, Sequence[str], None] = 'd5f4f14afbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS internal")

    op.create_table('migration_log',
    sa.Column('migration_id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
    sa.Column('revision', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('info', sa.String(), server_default=sa.text("'No more info included'"), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('migration_id'),
    schema='internal',
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    print("Rolling back migration logs could break some stuff\n")
    print("Continue (if you know what you are doing), by uncommenting line 44/45 in '994b2fac8a00_add_migration_log.py'")
    #op.drop_table('migration_log', schema='internal')
    #op.execute("DROP SCHEMA IF EXISTS internal")
    # ### end Alembic commands ###