"""fix api_key error

Revision ID: a0ab061a5bbd
Revises: c37fe0d02922
Create Date: 2026-02-15 02:31:29.274126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ab061a5bbd'
down_revision: Union[str, Sequence[str], None] = 'c37fe0d02922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_auth', 'api_key_hash',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_auth', 'api_key_hash',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='users')
    # ### end Alembic commands ###
