"""init schema

Revision ID: c16c48c31586
Revises: 
Create Date: 2026-01-25 02:32:08.594884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16c48c31586'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username'),
    schema='users'
    )
    op.create_table('user_auth',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    op.create_table('user_perm',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_perm', schema='users')
    op.drop_table('user_auth', schema='users')
    op.drop_table('user', schema='users')
    # ### end Alembic commands ###
