"""add metric tables

Revision ID: cc082cfc30f5
Revises: 5441ed5a5756
Create Date: 2026-02-17 17:02:18.429385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc082cfc30f5'
down_revision: Union[str, Sequence[str], None] = '5441ed5a5756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE SCHEMA IF NOT EXISTS metrics")

    op.create_table('global_metrics',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time'),
    schema='metrics'
    )
    op.create_table('route_metrics',
    sa.Column('time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('min_response_time', sa.Float(), nullable=True),
    sa.Column('max_response_time', sa.Float(), nullable=True),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p95', sa.Float(), nullable=True),
    sa.Column('p99', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'route'),
    schema='metrics'
    )
    op.create_table('route_status_codes',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'route', 'status_code'),
    schema='metrics'
    )


    try:
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")

        op.execute(
            "SELECT create_hypertable('metrics.route_metrics','time', if_not_exists => TRUE);"
        )

        op.execute(
            "SELECT create_hypertable('metrics.route_status_codes','time', if_not_exists => TRUE);"
        )

    except Exception as e:
        print(f"\n\nException while creating hypertable in cc082cfc30f5: {e}\n\n")
        print("This is most likely because the TimescaleDB extention is not installed for postgresql.\n")
        print("Please rebuild the postgresql docker container.\n")
        print("You'll need to backup the database.\n")
        print("For help create an issue.")
        exit(1)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
        SELECT drop_hypertable('metrics.route_status_codes', if_exists => TRUE);
    """)

    op.execute("""
        SELECT drop_hypertable('metrics.route_metrics', if_exists => TRUE);
    """)

    op.drop_table('route_status_codes', schema='metrics')
    op.drop_table('route_metrics', schema='metrics')
    op.drop_table('global_metrics', schema='metrics')

    op.execute("DROP EXTENSION IF EXISTS timescaledb CASCADE;")

    # ### end Alembic commands ###