"""revert of another test migration

Revision ID: d5f4f14afbe6
Revises: dd1d0f6e56ca
Create Date: 2026-01-28 20:29:18.553213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f4f14afbe6'
down_revision: Union[str, Sequence[str], None] = 'dd1d0f6e56ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table', schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('test_table_pkey')),
    schema='users'
    )
    # ### end Alembic commands ###
