"""another test migration

Revision ID: dd1d0f6e56ca
Revises: 546a9c0f4f47
Create Date: 2026-01-28 20:26:59.737208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1d0f6e56ca'
down_revision: Union[str, Sequence[str], None] = '546a9c0f4f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table', schema='users')
    # ### end Alembic commands ###
