"""testing migration logs

Revision ID: eb7048e0182f
Revises: 994b2fac8a00
Create Date: 2026-01-30 23:53:07.317508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7048e0182f'
down_revision: Union[str, Sequence[str], None] = '994b2fac8a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testg',
    sa.Column('test_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('test_id'),
    schema='internal'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testg', schema='internal')
    # ### end Alembic commands ###
