"""fixed not-null constraint for user table

Revision ID: f71c56d56452
Revises: f97e0bcde1b2
Create Date: 2026-02-04 19:32:30.427556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71c56d56452'
down_revision: Union[str, Sequence[str], None] = 'f97e0bcde1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='users')
    # ### end Alembic commands ###
