"""migration for test purpose

Revision ID: f92d00933ffa
Revises: 2c3b46f94269
Create Date: 2026-01-28 19:49:58.046426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92d00933ffa'
down_revision: Union[str, Sequence[str], None] = '2c3b46f94269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table', schema='users')
    # ### end Alembic commands ###
