"""fixed missing unique attribute for api_key

Revision ID: f97e0bcde1b2
Revises: 8012d775a881
Create Date: 2026-02-02 21:37:27.848800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97e0bcde1b2'
down_revision: Union[str, Sequence[str], None] = '8012d775a881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_auth', ['api_key_hash'], schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_auth', schema='users', type_='unique')
    # ### end Alembic commands ###
